#### Problem Statement: Given the data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,
- 2 yr experience, 9 test score, 6 interview score
- 12 yr experience, 10 test score, 10 interview score

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
df.experience = df.experience.fillna('zero')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [23]:
df = df.rename(columns={"experience":"experience",
                  "test_score(out of 10)":"test_score",
                  "interview_score(out of 10)": "interview_score",
                  "salary($)":"salary"})

df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [24]:
df.test_score = df.test_score.fillna(df.test_score.median())

In [25]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [28]:
from word2number import w2n

In [34]:
df.experience

0      zero
1      zero
2      five
3       two
4     seven
5     three
6       ten
7    eleven
Name: experience, dtype: object

In [35]:
df.experience = df.experience.apply(w2n.word_to_num)

In [36]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [38]:
from sklearn import linear_model

In [39]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('salary',axis='columns'),df.salary)

LinearRegression()

In [40]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [41]:
reg.intercept_

17737.26346433771

##### 2 yr experience, 9 test score, 6 interview score

In [48]:
reg.predict(np.array([2,9,6]).reshape(1,-1))

array([53205.96797671])

In [49]:
2812.95487627*2+1845.70596798*9+2205.24017467*6 +17737.26346433771

53205.967976717715

##### 12 yr experience, 10 test score, 10 interview score

In [50]:
reg.predict(np.array([12,10,10]).reshape(1,-1))

array([92002.18340611])

In [51]:
2812.95487627*12+1845.70596798*10+2205.24017467*10 +17737.26346433771

92002.1834060777